### ISSUE TITLE
  Error: docker not found! Please install it.  at dockerCommand 

### ISSUE THREAD

**Issue by chamathpali** [RGU-Computing/clood#14]
@ike01 Need to fix or add in the readme on how to solve the issue. Is it directly from **dockerZip: false**?

**Comment by ike01** [comment]
We use docker so it needs to have the docker daemon running in the background and **dockerizePip: true**

**Comment by chamathpali** [comment]
Thanks. Yes Installing docker and running docker in the background before doing `sls deploy` fixed the issue
